/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://jpegshi5szanxhheyr7gdkn46m.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-ojmky3sct5hk5gg4jqkwmf33aa",
    "aws_cognito_identity_pool_id": "us-east-1:bb9f7a84-d03a-42ad-9bc1-bb86d16a5bdd",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_9JQaj6WoE",
    "aws_user_pools_web_client_id": "76fc6q6iv4q5frfn0dq1h0hfb6",
    "oauth": {}
};


export default awsmobile;
